---

- name: Get all
  tags:
    - test1
  debug:
    msg: "{{ item.key}}:{{ item.value }}"
  with_dict: "{{ vgs }}"


- name: Get free_g
  tags:
    - test2
  debug:
    msg: "{{ item.key }}:{{ item.value.free_g }}"
  with_dict: "{{ vgs }}"


- name: Get free_g when not 0
  tags:
    - test3
  debug:
    msg: "{{ item.key }}:{{ item.value.free_g }}"
  with_dict: "{{ vgs }}"
  when: "{{ item.value.free_g }} != 0"


- name: Get free_g when not 0
  tags:
    - test4
  debug:
    msg: "{{ item.key }}:{{ item.value.free_g }}"
  with_dict: "{{ vgs }}"
  when:  item.value.free_g != "0"

#- name: Initialize free
#  tags:
#    - test5
#  set_fact:
#    free: []
      

- name: Set fact when not 0
  tags:
    - test5
  set_fact:
    free: "{{ free }} +  ['{{ item.key }}:{{item.value.free_g}}']"
  with_dict: "{{ vgs }}"
  when: item.value.free_g != "0"
  delegate_to: localhost


- name: Print fact
  tags:
    - test5
  debug:
    msg: "{{ free }}"

- name: Print fact
  tags:
    - test5
  debug:
    msg: "{{ free }}"
  delegate_to: localhost
