---


- name: "Create patset"
  tags:
    - test1
  debug:
    msg: "http://10.1.3.205/nitro/v1/config/policypatset/{{ item }}"
  with_items: "{{ patset }}"
  delegate_to: localhost


- name: Bind URLs to patset
  tags:
    - test2
  debug:
    msg: "http://10.1.3.205/nitro/v1/config/policypatset_pattern_binding/{{ item.key }}?args=String:{{ item | regex_replace('/', '%2F')}}"
  with_dict: "{{ patset }}"
  delegate_to: localhost

- name: Print patset json body
  tags:
    - test3
  debug:
    msg: "{{ item }}"
  with_items: "{{ patset | to_json}}"
  delegate_to: localhost
