---


- name: Create servers (module)
  tags:
    - create_servers_module
    - module
  delegate_to: localhost
  netscaler_server:
    nsip: "{{ ns_ip }}"
    validate_certs: no
    nitro_user: "{{ ns_user }}"
    nitro_pass: "{{ ns_pass }}"
    state: present

    name: "{{ item.name }}"
    ipaddress: "{{ item.ipaddress }}"
  with_items: "{{ servers.server }}"


- name: Create servers (uri)
  delegate_to: localhost
  tags:
    - create_servers_uri
    - uri
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/server?action=add"
    method: POST
    status_code: 201, 599
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"server": {{ item.value | to_json }} }'
  register: add_servers
  with_dict: "{{ servers }}"
  fail_when: "'already exists' not in add_servers.content"
